version: 0.2
phases:
  install:
    commands:
      - aws --version
      - echo "SRC=$CODEBUILD_SRC_DIR"
      - echo "Deploying $WEBSITE_DIR -> s3://$BUCKET_NAME"
      - |
        if [ ! -d "$WEBSITE_DIR" ]; then
          echo "ERROR: '$WEBSITE_DIR' not found. Here’s the top-level tree:"; find . -maxdepth 3 -type d
          exit 1
        fi
  build:
    commands:
      - >
        aws s3 sync "$WEBSITE_DIR/" "s3://$BUCKET_NAME/"
        --delete
        --exclude "*.html"
        --cache-control "max-age=31536000,public"
      - >
        aws s3 sync "$WEBSITE_DIR/" "s3://$BUCKET_NAME/"
        --exclude "*"
        --include "*.html"
        --cache-control "no-cache"
      - |
        if [ -n "${DISTRIBUTION_ID:-}" ]; then
          PATHS=$(cd "$WEBSITE_DIR" && find . -type f -name "*.html" -printf "/%P ")
          [ -n "$PATHS" ] && aws cloudfront create-invalidation --distribution-id "$DISTRIBUTION_ID" --paths $PATHS
        fi
