version: 0.2
phases:
  install:
    commands:
      - aws --version
      - echo "Deploying $WEBSITE_DIR to s3://$BUCKET_NAME"
  build:
    commands:
      # 1) Assets (long cache)
      - >
        aws s3 sync "$WEBSITE_DIR/" "s3://$BUCKET_NAME/"
        --delete
        --exclude "*.html"
        --cache-control "max-age=31536000,public"

      # 2) HTML (no-cache so edits show immediately)
      - >
        aws s3 sync "$WEBSITE_DIR/" "s3://$BUCKET_NAME/"
        --exclude "*"
        --include "*.html"
        --cache-control "no-cache"

      # 3) Optional: invalidate HTML at the edge
      - |
        if [ -n "${DISTRIBUTION_ID:-}" ]; then
          PATHS=$(cd "$WEBSITE_DIR" && find . -type f -name "*.html" -printf "/%P ")
          [ -n "$PATHS" ] && aws cloudfront create-invalidation --distribution-id "$DISTRIBUTION_ID" --paths $PATHS
        fi
